apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matomo
  namespace: matomo
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`stats.lalux.lu`)    # Just match the hostname
      kind: Rule
      middlewares:
        - name: secure-headers
      services:
        - name: nginx-matomo
          port: 80

