apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-matomo-pvc
  namespace: matomo
  labels:
    app: matomo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi


