apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matomo
  labels:
    app: db-matomo
    tier: db
  name: db-matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-matomo
  template:
    metadata:
      labels:
        app: db-matomo
    spec:
      containers:
      - image: mariadb
        name: mariadb
        ports:
          - containerPort: 3306
        envFrom:
              - configMapRef:
                        name: db-matomo-envs
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-matomo-secrets
                key: mariadb-root-password
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-matomo-secrets
                key: mariadb-password
        volumeMounts:
          - name: matomo-db-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: matomo-db-volume
          persistentVolumeClaim:
            claimName: db-matomo-pvc

    

