apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-matomo
    tier: db
  name: db-matomo
  namespace: matomo
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db-matomo
  type: ClusterIP
