apiVersion: v1
kind: Service
metadata:
  name: nginx-matomo
  namespace: matomo
  labels:
    app: nginx-matomo
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-matomo
    tier: frontend

