apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-matomo-html-data
  namespace: matomo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-matomo-php-logs
  namespace: matomo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client


