apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-matomo
    tier: backend
  name: php-matomo
  namespace: matomo
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: php-matomo
    tier: backend
